#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaDatos
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="dbPortafolioDocentes")]
	public partial class ConexionLinqDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Definiciones de métodos de extensibilidad
    partial void OnCreated();
    partial void InserttDocente(tDocente instance);
    partial void UpdatetDocente(tDocente instance);
    partial void DeletetDocente(tDocente instance);
    partial void InserttPerfil(tPerfil instance);
    partial void UpdatetPerfil(tPerfil instance);
    partial void DeletetPerfil(tPerfil instance);
    partial void InserttDetallePortafolio(tDetallePortafolio instance);
    partial void UpdatetDetallePortafolio(tDetallePortafolio instance);
    partial void DeletetDetallePortafolio(tDetallePortafolio instance);
    partial void InserttPortafolio(tPortafolio instance);
    partial void UpdatetPortafolio(tPortafolio instance);
    partial void DeletetPortafolio(tPortafolio instance);
    partial void InserttPrivilegios(tPrivilegios instance);
    partial void UpdatetPrivilegios(tPrivilegios instance);
    partial void DeletetPrivilegios(tPrivilegios instance);
    partial void InserttUsuario(tUsuario instance);
    partial void UpdatetUsuario(tUsuario instance);
    partial void DeletetUsuario(tUsuario instance);
    #endregion
		
		public ConexionLinqDataContext() : 
				base(global::CapaDatos.Properties.Settings.Default.dbPortafolioDocentesConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public ConexionLinqDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ConexionLinqDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ConexionLinqDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ConexionLinqDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<tDocente> tDocente
		{
			get
			{
				return this.GetTable<tDocente>();
			}
		}
		
		public System.Data.Linq.Table<tPerfil> tPerfil
		{
			get
			{
				return this.GetTable<tPerfil>();
			}
		}
		
		public System.Data.Linq.Table<tDetallePortafolio> tDetallePortafolio
		{
			get
			{
				return this.GetTable<tDetallePortafolio>();
			}
		}
		
		public System.Data.Linq.Table<tPortafolio> tPortafolio
		{
			get
			{
				return this.GetTable<tPortafolio>();
			}
		}
		
		public System.Data.Linq.Table<tPrivilegios> tPrivilegios
		{
			get
			{
				return this.GetTable<tPrivilegios>();
			}
		}
		
		public System.Data.Linq.Table<tUsuario> tUsuario
		{
			get
			{
				return this.GetTable<tUsuario>();
			}
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.spInsertar_Docente")]
		public int spInsertar_Docente([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(8)")] string iddocente, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(30)")] string nombres, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string apellidopat, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string apellidomat, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(8)")] string dni, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(12)")] string telefono, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string direccion, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] ref string mjs)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), iddocente, nombres, apellidopat, apellidomat, dni, telefono, direccion, mjs);
			mjs = ((string)(result.GetParameterValue(7)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.spActualizar_Docente")]
		public int spActualizar_Docente([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(8)")] string iddocente, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(30)")] string nombre, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string apellidopat, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string apellidomat, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(8)")] string dni, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(12)")] string telefono, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string direccion, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] ref string mjs)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), iddocente, nombre, apellidopat, apellidomat, dni, telefono, direccion, mjs);
			mjs = ((string)(result.GetParameterValue(7)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.spEliminar_Docente")]
		public int spEliminar_Docente([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(8)")] string iddocente, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] ref string mjs)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), iddocente, mjs);
			mjs = ((string)(result.GetParameterValue(1)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.spBuscar_Docente")]
		public ISingleResult<spBuscar_DocenteResult> spBuscar_Docente([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(8)")] string idDocente, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] ref string mjs)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idDocente, mjs);
			mjs = ((string)(result.GetParameterValue(1)));
			return ((ISingleResult<spBuscar_DocenteResult>)(result.ReturnValue));
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tDocente")]
	public partial class tDocente : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _idDocente;
		
		private string _Nombre;
		
		private string _ApellidoPat;
		
		private string _ApellidoMat;
		
		private string _DNI;
		
		private string _Telefono;
		
		private string _Direccion;
		
		private EntitySet<tDetallePortafolio> _tDetallePortafolio;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidDocenteChanging(string value);
    partial void OnidDocenteChanged();
    partial void OnNombreChanging(string value);
    partial void OnNombreChanged();
    partial void OnApellidoPatChanging(string value);
    partial void OnApellidoPatChanged();
    partial void OnApellidoMatChanging(string value);
    partial void OnApellidoMatChanged();
    partial void OnDNIChanging(string value);
    partial void OnDNIChanged();
    partial void OnTelefonoChanging(string value);
    partial void OnTelefonoChanged();
    partial void OnDireccionChanging(string value);
    partial void OnDireccionChanged();
    #endregion
		
		public tDocente()
		{
			this._tDetallePortafolio = new EntitySet<tDetallePortafolio>(new Action<tDetallePortafolio>(this.attach_tDetallePortafolio), new Action<tDetallePortafolio>(this.detach_tDetallePortafolio));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idDocente", DbType="VarChar(8) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string idDocente
		{
			get
			{
				return this._idDocente;
			}
			set
			{
				if ((this._idDocente != value))
				{
					this.OnidDocenteChanging(value);
					this.SendPropertyChanging();
					this._idDocente = value;
					this.SendPropertyChanged("idDocente");
					this.OnidDocenteChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombre", DbType="VarChar(30) NOT NULL", CanBeNull=false)]
		public string Nombre
		{
			get
			{
				return this._Nombre;
			}
			set
			{
				if ((this._Nombre != value))
				{
					this.OnNombreChanging(value);
					this.SendPropertyChanging();
					this._Nombre = value;
					this.SendPropertyChanged("Nombre");
					this.OnNombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ApellidoPat", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string ApellidoPat
		{
			get
			{
				return this._ApellidoPat;
			}
			set
			{
				if ((this._ApellidoPat != value))
				{
					this.OnApellidoPatChanging(value);
					this.SendPropertyChanging();
					this._ApellidoPat = value;
					this.SendPropertyChanged("ApellidoPat");
					this.OnApellidoPatChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ApellidoMat", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string ApellidoMat
		{
			get
			{
				return this._ApellidoMat;
			}
			set
			{
				if ((this._ApellidoMat != value))
				{
					this.OnApellidoMatChanging(value);
					this.SendPropertyChanging();
					this._ApellidoMat = value;
					this.SendPropertyChanged("ApellidoMat");
					this.OnApellidoMatChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DNI", DbType="VarChar(8) NOT NULL", CanBeNull=false)]
		public string DNI
		{
			get
			{
				return this._DNI;
			}
			set
			{
				if ((this._DNI != value))
				{
					this.OnDNIChanging(value);
					this.SendPropertyChanging();
					this._DNI = value;
					this.SendPropertyChanged("DNI");
					this.OnDNIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Telefono", DbType="VarChar(12)")]
		public string Telefono
		{
			get
			{
				return this._Telefono;
			}
			set
			{
				if ((this._Telefono != value))
				{
					this.OnTelefonoChanging(value);
					this.SendPropertyChanging();
					this._Telefono = value;
					this.SendPropertyChanged("Telefono");
					this.OnTelefonoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Direccion", DbType="VarChar(50)")]
		public string Direccion
		{
			get
			{
				return this._Direccion;
			}
			set
			{
				if ((this._Direccion != value))
				{
					this.OnDireccionChanging(value);
					this.SendPropertyChanging();
					this._Direccion = value;
					this.SendPropertyChanged("Direccion");
					this.OnDireccionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tDocente_tDetallePortafolio", Storage="_tDetallePortafolio", ThisKey="idDocente", OtherKey="idDocente")]
		public EntitySet<tDetallePortafolio> tDetallePortafolio
		{
			get
			{
				return this._tDetallePortafolio;
			}
			set
			{
				this._tDetallePortafolio.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tDetallePortafolio(tDetallePortafolio entity)
		{
			this.SendPropertyChanging();
			entity.tDocente = this;
		}
		
		private void detach_tDetallePortafolio(tDetallePortafolio entity)
		{
			this.SendPropertyChanging();
			entity.tDocente = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tPerfil")]
	public partial class tPerfil : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _idPerfil;
		
		private string _idPrivilegios;
		
		private string _Rol;
		
		private EntitySet<tUsuario> _tUsuario;
		
		private EntityRef<tPrivilegios> _tPrivilegios;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidPerfilChanging(string value);
    partial void OnidPerfilChanged();
    partial void OnidPrivilegiosChanging(string value);
    partial void OnidPrivilegiosChanged();
    partial void OnRolChanging(string value);
    partial void OnRolChanged();
    #endregion
		
		public tPerfil()
		{
			this._tUsuario = new EntitySet<tUsuario>(new Action<tUsuario>(this.attach_tUsuario), new Action<tUsuario>(this.detach_tUsuario));
			this._tPrivilegios = default(EntityRef<tPrivilegios>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idPerfil", DbType="VarChar(8) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string idPerfil
		{
			get
			{
				return this._idPerfil;
			}
			set
			{
				if ((this._idPerfil != value))
				{
					this.OnidPerfilChanging(value);
					this.SendPropertyChanging();
					this._idPerfil = value;
					this.SendPropertyChanged("idPerfil");
					this.OnidPerfilChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idPrivilegios", DbType="VarChar(8) NOT NULL", CanBeNull=false)]
		public string idPrivilegios
		{
			get
			{
				return this._idPrivilegios;
			}
			set
			{
				if ((this._idPrivilegios != value))
				{
					if (this._tPrivilegios.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnidPrivilegiosChanging(value);
					this.SendPropertyChanging();
					this._idPrivilegios = value;
					this.SendPropertyChanged("idPrivilegios");
					this.OnidPrivilegiosChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Rol", DbType="VarChar(40) NOT NULL", CanBeNull=false)]
		public string Rol
		{
			get
			{
				return this._Rol;
			}
			set
			{
				if ((this._Rol != value))
				{
					this.OnRolChanging(value);
					this.SendPropertyChanging();
					this._Rol = value;
					this.SendPropertyChanged("Rol");
					this.OnRolChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tPerfil_tUsuario", Storage="_tUsuario", ThisKey="idPerfil", OtherKey="idPerfil")]
		public EntitySet<tUsuario> tUsuario
		{
			get
			{
				return this._tUsuario;
			}
			set
			{
				this._tUsuario.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tPrivilegios_tPerfil", Storage="_tPrivilegios", ThisKey="idPrivilegios", OtherKey="idPrivilegios", IsForeignKey=true)]
		public tPrivilegios tPrivilegios
		{
			get
			{
				return this._tPrivilegios.Entity;
			}
			set
			{
				tPrivilegios previousValue = this._tPrivilegios.Entity;
				if (((previousValue != value) 
							|| (this._tPrivilegios.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tPrivilegios.Entity = null;
						previousValue.tPerfil.Remove(this);
					}
					this._tPrivilegios.Entity = value;
					if ((value != null))
					{
						value.tPerfil.Add(this);
						this._idPrivilegios = value.idPrivilegios;
					}
					else
					{
						this._idPrivilegios = default(string);
					}
					this.SendPropertyChanged("tPrivilegios");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tUsuario(tUsuario entity)
		{
			this.SendPropertyChanging();
			entity.tPerfil = this;
		}
		
		private void detach_tUsuario(tUsuario entity)
		{
			this.SendPropertyChanging();
			entity.tPerfil = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tDetallePortafolio")]
	public partial class tDetallePortafolio : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _idDocente;
		
		private string _idPortafolio;
		
		private EntityRef<tDocente> _tDocente;
		
		private EntityRef<tPortafolio> _tPortafolio;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidDocenteChanging(string value);
    partial void OnidDocenteChanged();
    partial void OnidPortafolioChanging(string value);
    partial void OnidPortafolioChanged();
    #endregion
		
		public tDetallePortafolio()
		{
			this._tDocente = default(EntityRef<tDocente>);
			this._tPortafolio = default(EntityRef<tPortafolio>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idDocente", DbType="VarChar(8) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string idDocente
		{
			get
			{
				return this._idDocente;
			}
			set
			{
				if ((this._idDocente != value))
				{
					if (this._tDocente.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnidDocenteChanging(value);
					this.SendPropertyChanging();
					this._idDocente = value;
					this.SendPropertyChanged("idDocente");
					this.OnidDocenteChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idPortafolio", DbType="VarChar(8) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string idPortafolio
		{
			get
			{
				return this._idPortafolio;
			}
			set
			{
				if ((this._idPortafolio != value))
				{
					if (this._tPortafolio.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnidPortafolioChanging(value);
					this.SendPropertyChanging();
					this._idPortafolio = value;
					this.SendPropertyChanged("idPortafolio");
					this.OnidPortafolioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tDocente_tDetallePortafolio", Storage="_tDocente", ThisKey="idDocente", OtherKey="idDocente", IsForeignKey=true)]
		public tDocente tDocente
		{
			get
			{
				return this._tDocente.Entity;
			}
			set
			{
				tDocente previousValue = this._tDocente.Entity;
				if (((previousValue != value) 
							|| (this._tDocente.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tDocente.Entity = null;
						previousValue.tDetallePortafolio.Remove(this);
					}
					this._tDocente.Entity = value;
					if ((value != null))
					{
						value.tDetallePortafolio.Add(this);
						this._idDocente = value.idDocente;
					}
					else
					{
						this._idDocente = default(string);
					}
					this.SendPropertyChanged("tDocente");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tPortafolio_tDetallePortafolio", Storage="_tPortafolio", ThisKey="idPortafolio", OtherKey="idPortafolio", IsForeignKey=true)]
		public tPortafolio tPortafolio
		{
			get
			{
				return this._tPortafolio.Entity;
			}
			set
			{
				tPortafolio previousValue = this._tPortafolio.Entity;
				if (((previousValue != value) 
							|| (this._tPortafolio.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tPortafolio.Entity = null;
						previousValue.tDetallePortafolio.Remove(this);
					}
					this._tPortafolio.Entity = value;
					if ((value != null))
					{
						value.tDetallePortafolio.Add(this);
						this._idPortafolio = value.idPortafolio;
					}
					else
					{
						this._idPortafolio = default(string);
					}
					this.SendPropertyChanged("tPortafolio");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tPortafolio")]
	public partial class tPortafolio : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _idPortafolio;
		
		private string _FilosofiaDocente;
		
		private string _Curriculum;
		
		private string _MisionVision;
		
		private string _ObjetivosEducacionales;
		
		private string _PerfilDeIngresanteEP;
		
		private string _PerfilEgresadoEP;
		
		private string _PlanDeEstudiosEP;
		
		private string _MallaCurricularEP;
		
		private string _RelacionEstudiantesMAtriculados;
		
		private string _RegistroAsistencia;
		
		private string _AvanceDeSesionesPorClase;
		
		private string _RegistroEntregaSilabo;
		
		private string _SilaboUnsaac;
		
		private string _SilaboIcacid;
		
		private string _PresentacionPowerPoint;
		
		private string _FichaLectura;
		
		private string _EjerciciosPracticos;
		
		private string _ActividadesInvestigacion;
		
		private string _GuiasLaboratorio;
		
		private string _TrabajoCampo;
		
		private string _Visitas;
		
		private string _ActividadesProyeccionSocial;
		
		private string _TextosEspecialidad;
		
		private string _Evauaciones;
		
		private string _ProyectosIndividualesGrupales;
		
		private string _Anexos;
		
		private EntitySet<tDetallePortafolio> _tDetallePortafolio;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidPortafolioChanging(string value);
    partial void OnidPortafolioChanged();
    partial void OnFilosofiaDocenteChanging(string value);
    partial void OnFilosofiaDocenteChanged();
    partial void OnCurriculumChanging(string value);
    partial void OnCurriculumChanged();
    partial void OnMisionVisionChanging(string value);
    partial void OnMisionVisionChanged();
    partial void OnObjetivosEducacionalesChanging(string value);
    partial void OnObjetivosEducacionalesChanged();
    partial void OnPerfilDeIngresanteEPChanging(string value);
    partial void OnPerfilDeIngresanteEPChanged();
    partial void OnPerfilEgresadoEPChanging(string value);
    partial void OnPerfilEgresadoEPChanged();
    partial void OnPlanDeEstudiosEPChanging(string value);
    partial void OnPlanDeEstudiosEPChanged();
    partial void OnMallaCurricularEPChanging(string value);
    partial void OnMallaCurricularEPChanged();
    partial void OnRelacionEstudiantesMAtriculadosChanging(string value);
    partial void OnRelacionEstudiantesMAtriculadosChanged();
    partial void OnRegistroAsistenciaChanging(string value);
    partial void OnRegistroAsistenciaChanged();
    partial void OnAvanceDeSesionesPorClaseChanging(string value);
    partial void OnAvanceDeSesionesPorClaseChanged();
    partial void OnRegistroEntregaSilaboChanging(string value);
    partial void OnRegistroEntregaSilaboChanged();
    partial void OnSilaboUnsaacChanging(string value);
    partial void OnSilaboUnsaacChanged();
    partial void OnSilaboIcacidChanging(string value);
    partial void OnSilaboIcacidChanged();
    partial void OnPresentacionPowerPointChanging(string value);
    partial void OnPresentacionPowerPointChanged();
    partial void OnFichaLecturaChanging(string value);
    partial void OnFichaLecturaChanged();
    partial void OnEjerciciosPracticosChanging(string value);
    partial void OnEjerciciosPracticosChanged();
    partial void OnActividadesInvestigacionChanging(string value);
    partial void OnActividadesInvestigacionChanged();
    partial void OnGuiasLaboratorioChanging(string value);
    partial void OnGuiasLaboratorioChanged();
    partial void OnTrabajoCampoChanging(string value);
    partial void OnTrabajoCampoChanged();
    partial void OnVisitasChanging(string value);
    partial void OnVisitasChanged();
    partial void OnActividadesProyeccionSocialChanging(string value);
    partial void OnActividadesProyeccionSocialChanged();
    partial void OnTextosEspecialidadChanging(string value);
    partial void OnTextosEspecialidadChanged();
    partial void OnEvauacionesChanging(string value);
    partial void OnEvauacionesChanged();
    partial void OnProyectosIndividualesGrupalesChanging(string value);
    partial void OnProyectosIndividualesGrupalesChanged();
    partial void OnAnexosChanging(string value);
    partial void OnAnexosChanged();
    #endregion
		
		public tPortafolio()
		{
			this._tDetallePortafolio = new EntitySet<tDetallePortafolio>(new Action<tDetallePortafolio>(this.attach_tDetallePortafolio), new Action<tDetallePortafolio>(this.detach_tDetallePortafolio));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idPortafolio", DbType="VarChar(8) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string idPortafolio
		{
			get
			{
				return this._idPortafolio;
			}
			set
			{
				if ((this._idPortafolio != value))
				{
					this.OnidPortafolioChanging(value);
					this.SendPropertyChanging();
					this._idPortafolio = value;
					this.SendPropertyChanged("idPortafolio");
					this.OnidPortafolioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FilosofiaDocente", DbType="Char(100)")]
		public string FilosofiaDocente
		{
			get
			{
				return this._FilosofiaDocente;
			}
			set
			{
				if ((this._FilosofiaDocente != value))
				{
					this.OnFilosofiaDocenteChanging(value);
					this.SendPropertyChanging();
					this._FilosofiaDocente = value;
					this.SendPropertyChanged("FilosofiaDocente");
					this.OnFilosofiaDocenteChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Curriculum", DbType="Char(100)")]
		public string Curriculum
		{
			get
			{
				return this._Curriculum;
			}
			set
			{
				if ((this._Curriculum != value))
				{
					this.OnCurriculumChanging(value);
					this.SendPropertyChanging();
					this._Curriculum = value;
					this.SendPropertyChanged("Curriculum");
					this.OnCurriculumChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MisionVision", DbType="Char(100)")]
		public string MisionVision
		{
			get
			{
				return this._MisionVision;
			}
			set
			{
				if ((this._MisionVision != value))
				{
					this.OnMisionVisionChanging(value);
					this.SendPropertyChanging();
					this._MisionVision = value;
					this.SendPropertyChanged("MisionVision");
					this.OnMisionVisionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ObjetivosEducacionales", DbType="Char(100)")]
		public string ObjetivosEducacionales
		{
			get
			{
				return this._ObjetivosEducacionales;
			}
			set
			{
				if ((this._ObjetivosEducacionales != value))
				{
					this.OnObjetivosEducacionalesChanging(value);
					this.SendPropertyChanging();
					this._ObjetivosEducacionales = value;
					this.SendPropertyChanged("ObjetivosEducacionales");
					this.OnObjetivosEducacionalesChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PerfilDeIngresanteEP", DbType="Char(100)")]
		public string PerfilDeIngresanteEP
		{
			get
			{
				return this._PerfilDeIngresanteEP;
			}
			set
			{
				if ((this._PerfilDeIngresanteEP != value))
				{
					this.OnPerfilDeIngresanteEPChanging(value);
					this.SendPropertyChanging();
					this._PerfilDeIngresanteEP = value;
					this.SendPropertyChanged("PerfilDeIngresanteEP");
					this.OnPerfilDeIngresanteEPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PerfilEgresadoEP", DbType="Char(100)")]
		public string PerfilEgresadoEP
		{
			get
			{
				return this._PerfilEgresadoEP;
			}
			set
			{
				if ((this._PerfilEgresadoEP != value))
				{
					this.OnPerfilEgresadoEPChanging(value);
					this.SendPropertyChanging();
					this._PerfilEgresadoEP = value;
					this.SendPropertyChanged("PerfilEgresadoEP");
					this.OnPerfilEgresadoEPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PlanDeEstudiosEP", DbType="Char(100)")]
		public string PlanDeEstudiosEP
		{
			get
			{
				return this._PlanDeEstudiosEP;
			}
			set
			{
				if ((this._PlanDeEstudiosEP != value))
				{
					this.OnPlanDeEstudiosEPChanging(value);
					this.SendPropertyChanging();
					this._PlanDeEstudiosEP = value;
					this.SendPropertyChanged("PlanDeEstudiosEP");
					this.OnPlanDeEstudiosEPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MallaCurricularEP", DbType="Char(100)")]
		public string MallaCurricularEP
		{
			get
			{
				return this._MallaCurricularEP;
			}
			set
			{
				if ((this._MallaCurricularEP != value))
				{
					this.OnMallaCurricularEPChanging(value);
					this.SendPropertyChanging();
					this._MallaCurricularEP = value;
					this.SendPropertyChanged("MallaCurricularEP");
					this.OnMallaCurricularEPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RelacionEstudiantesMAtriculados", DbType="Char(100)")]
		public string RelacionEstudiantesMAtriculados
		{
			get
			{
				return this._RelacionEstudiantesMAtriculados;
			}
			set
			{
				if ((this._RelacionEstudiantesMAtriculados != value))
				{
					this.OnRelacionEstudiantesMAtriculadosChanging(value);
					this.SendPropertyChanging();
					this._RelacionEstudiantesMAtriculados = value;
					this.SendPropertyChanged("RelacionEstudiantesMAtriculados");
					this.OnRelacionEstudiantesMAtriculadosChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RegistroAsistencia", DbType="Char(100)")]
		public string RegistroAsistencia
		{
			get
			{
				return this._RegistroAsistencia;
			}
			set
			{
				if ((this._RegistroAsistencia != value))
				{
					this.OnRegistroAsistenciaChanging(value);
					this.SendPropertyChanging();
					this._RegistroAsistencia = value;
					this.SendPropertyChanged("RegistroAsistencia");
					this.OnRegistroAsistenciaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AvanceDeSesionesPorClase", DbType="Char(100)")]
		public string AvanceDeSesionesPorClase
		{
			get
			{
				return this._AvanceDeSesionesPorClase;
			}
			set
			{
				if ((this._AvanceDeSesionesPorClase != value))
				{
					this.OnAvanceDeSesionesPorClaseChanging(value);
					this.SendPropertyChanging();
					this._AvanceDeSesionesPorClase = value;
					this.SendPropertyChanged("AvanceDeSesionesPorClase");
					this.OnAvanceDeSesionesPorClaseChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RegistroEntregaSilabo", DbType="Char(500)")]
		public string RegistroEntregaSilabo
		{
			get
			{
				return this._RegistroEntregaSilabo;
			}
			set
			{
				if ((this._RegistroEntregaSilabo != value))
				{
					this.OnRegistroEntregaSilaboChanging(value);
					this.SendPropertyChanging();
					this._RegistroEntregaSilabo = value;
					this.SendPropertyChanged("RegistroEntregaSilabo");
					this.OnRegistroEntregaSilaboChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SilaboUnsaac", DbType="Char(100)")]
		public string SilaboUnsaac
		{
			get
			{
				return this._SilaboUnsaac;
			}
			set
			{
				if ((this._SilaboUnsaac != value))
				{
					this.OnSilaboUnsaacChanging(value);
					this.SendPropertyChanging();
					this._SilaboUnsaac = value;
					this.SendPropertyChanged("SilaboUnsaac");
					this.OnSilaboUnsaacChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SilaboIcacid", DbType="Char(100)")]
		public string SilaboIcacid
		{
			get
			{
				return this._SilaboIcacid;
			}
			set
			{
				if ((this._SilaboIcacid != value))
				{
					this.OnSilaboIcacidChanging(value);
					this.SendPropertyChanging();
					this._SilaboIcacid = value;
					this.SendPropertyChanged("SilaboIcacid");
					this.OnSilaboIcacidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PresentacionPowerPoint", DbType="Char(100)")]
		public string PresentacionPowerPoint
		{
			get
			{
				return this._PresentacionPowerPoint;
			}
			set
			{
				if ((this._PresentacionPowerPoint != value))
				{
					this.OnPresentacionPowerPointChanging(value);
					this.SendPropertyChanging();
					this._PresentacionPowerPoint = value;
					this.SendPropertyChanged("PresentacionPowerPoint");
					this.OnPresentacionPowerPointChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FichaLectura", DbType="Char(100)")]
		public string FichaLectura
		{
			get
			{
				return this._FichaLectura;
			}
			set
			{
				if ((this._FichaLectura != value))
				{
					this.OnFichaLecturaChanging(value);
					this.SendPropertyChanging();
					this._FichaLectura = value;
					this.SendPropertyChanged("FichaLectura");
					this.OnFichaLecturaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EjerciciosPracticos", DbType="Char(100)")]
		public string EjerciciosPracticos
		{
			get
			{
				return this._EjerciciosPracticos;
			}
			set
			{
				if ((this._EjerciciosPracticos != value))
				{
					this.OnEjerciciosPracticosChanging(value);
					this.SendPropertyChanging();
					this._EjerciciosPracticos = value;
					this.SendPropertyChanged("EjerciciosPracticos");
					this.OnEjerciciosPracticosChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ActividadesInvestigacion", DbType="Char(100)")]
		public string ActividadesInvestigacion
		{
			get
			{
				return this._ActividadesInvestigacion;
			}
			set
			{
				if ((this._ActividadesInvestigacion != value))
				{
					this.OnActividadesInvestigacionChanging(value);
					this.SendPropertyChanging();
					this._ActividadesInvestigacion = value;
					this.SendPropertyChanged("ActividadesInvestigacion");
					this.OnActividadesInvestigacionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GuiasLaboratorio", DbType="Char(100)")]
		public string GuiasLaboratorio
		{
			get
			{
				return this._GuiasLaboratorio;
			}
			set
			{
				if ((this._GuiasLaboratorio != value))
				{
					this.OnGuiasLaboratorioChanging(value);
					this.SendPropertyChanging();
					this._GuiasLaboratorio = value;
					this.SendPropertyChanged("GuiasLaboratorio");
					this.OnGuiasLaboratorioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TrabajoCampo", DbType="Char(100)")]
		public string TrabajoCampo
		{
			get
			{
				return this._TrabajoCampo;
			}
			set
			{
				if ((this._TrabajoCampo != value))
				{
					this.OnTrabajoCampoChanging(value);
					this.SendPropertyChanging();
					this._TrabajoCampo = value;
					this.SendPropertyChanged("TrabajoCampo");
					this.OnTrabajoCampoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Visitas", DbType="Char(100)")]
		public string Visitas
		{
			get
			{
				return this._Visitas;
			}
			set
			{
				if ((this._Visitas != value))
				{
					this.OnVisitasChanging(value);
					this.SendPropertyChanging();
					this._Visitas = value;
					this.SendPropertyChanged("Visitas");
					this.OnVisitasChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ActividadesProyeccionSocial", DbType="Char(100)")]
		public string ActividadesProyeccionSocial
		{
			get
			{
				return this._ActividadesProyeccionSocial;
			}
			set
			{
				if ((this._ActividadesProyeccionSocial != value))
				{
					this.OnActividadesProyeccionSocialChanging(value);
					this.SendPropertyChanging();
					this._ActividadesProyeccionSocial = value;
					this.SendPropertyChanged("ActividadesProyeccionSocial");
					this.OnActividadesProyeccionSocialChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TextosEspecialidad", DbType="Char(100)")]
		public string TextosEspecialidad
		{
			get
			{
				return this._TextosEspecialidad;
			}
			set
			{
				if ((this._TextosEspecialidad != value))
				{
					this.OnTextosEspecialidadChanging(value);
					this.SendPropertyChanging();
					this._TextosEspecialidad = value;
					this.SendPropertyChanged("TextosEspecialidad");
					this.OnTextosEspecialidadChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Evauaciones", DbType="Char(100)")]
		public string Evauaciones
		{
			get
			{
				return this._Evauaciones;
			}
			set
			{
				if ((this._Evauaciones != value))
				{
					this.OnEvauacionesChanging(value);
					this.SendPropertyChanging();
					this._Evauaciones = value;
					this.SendPropertyChanged("Evauaciones");
					this.OnEvauacionesChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProyectosIndividualesGrupales", DbType="Char(100)")]
		public string ProyectosIndividualesGrupales
		{
			get
			{
				return this._ProyectosIndividualesGrupales;
			}
			set
			{
				if ((this._ProyectosIndividualesGrupales != value))
				{
					this.OnProyectosIndividualesGrupalesChanging(value);
					this.SendPropertyChanging();
					this._ProyectosIndividualesGrupales = value;
					this.SendPropertyChanged("ProyectosIndividualesGrupales");
					this.OnProyectosIndividualesGrupalesChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Anexos", DbType="Char(100)")]
		public string Anexos
		{
			get
			{
				return this._Anexos;
			}
			set
			{
				if ((this._Anexos != value))
				{
					this.OnAnexosChanging(value);
					this.SendPropertyChanging();
					this._Anexos = value;
					this.SendPropertyChanged("Anexos");
					this.OnAnexosChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tPortafolio_tDetallePortafolio", Storage="_tDetallePortafolio", ThisKey="idPortafolio", OtherKey="idPortafolio")]
		public EntitySet<tDetallePortafolio> tDetallePortafolio
		{
			get
			{
				return this._tDetallePortafolio;
			}
			set
			{
				this._tDetallePortafolio.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tDetallePortafolio(tDetallePortafolio entity)
		{
			this.SendPropertyChanging();
			entity.tPortafolio = this;
		}
		
		private void detach_tDetallePortafolio(tDetallePortafolio entity)
		{
			this.SendPropertyChanging();
			entity.tPortafolio = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tPrivilegios")]
	public partial class tPrivilegios : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _idPrivilegios;
		
		private string _Administrador;
		
		private string _UsuarioPrincipal;
		
		private string _UsuarioComun;
		
		private EntitySet<tPerfil> _tPerfil;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidPrivilegiosChanging(string value);
    partial void OnidPrivilegiosChanged();
    partial void OnAdministradorChanging(string value);
    partial void OnAdministradorChanged();
    partial void OnUsuarioPrincipalChanging(string value);
    partial void OnUsuarioPrincipalChanged();
    partial void OnUsuarioComunChanging(string value);
    partial void OnUsuarioComunChanged();
    #endregion
		
		public tPrivilegios()
		{
			this._tPerfil = new EntitySet<tPerfil>(new Action<tPerfil>(this.attach_tPerfil), new Action<tPerfil>(this.detach_tPerfil));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idPrivilegios", DbType="VarChar(8) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string idPrivilegios
		{
			get
			{
				return this._idPrivilegios;
			}
			set
			{
				if ((this._idPrivilegios != value))
				{
					this.OnidPrivilegiosChanging(value);
					this.SendPropertyChanging();
					this._idPrivilegios = value;
					this.SendPropertyChanged("idPrivilegios");
					this.OnidPrivilegiosChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Administrador", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string Administrador
		{
			get
			{
				return this._Administrador;
			}
			set
			{
				if ((this._Administrador != value))
				{
					this.OnAdministradorChanging(value);
					this.SendPropertyChanging();
					this._Administrador = value;
					this.SendPropertyChanged("Administrador");
					this.OnAdministradorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UsuarioPrincipal", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string UsuarioPrincipal
		{
			get
			{
				return this._UsuarioPrincipal;
			}
			set
			{
				if ((this._UsuarioPrincipal != value))
				{
					this.OnUsuarioPrincipalChanging(value);
					this.SendPropertyChanging();
					this._UsuarioPrincipal = value;
					this.SendPropertyChanged("UsuarioPrincipal");
					this.OnUsuarioPrincipalChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UsuarioComun", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string UsuarioComun
		{
			get
			{
				return this._UsuarioComun;
			}
			set
			{
				if ((this._UsuarioComun != value))
				{
					this.OnUsuarioComunChanging(value);
					this.SendPropertyChanging();
					this._UsuarioComun = value;
					this.SendPropertyChanged("UsuarioComun");
					this.OnUsuarioComunChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tPrivilegios_tPerfil", Storage="_tPerfil", ThisKey="idPrivilegios", OtherKey="idPrivilegios")]
		public EntitySet<tPerfil> tPerfil
		{
			get
			{
				return this._tPerfil;
			}
			set
			{
				this._tPerfil.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tPerfil(tPerfil entity)
		{
			this.SendPropertyChanging();
			entity.tPrivilegios = this;
		}
		
		private void detach_tPerfil(tPerfil entity)
		{
			this.SendPropertyChanging();
			entity.tPrivilegios = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tUsuario")]
	public partial class tUsuario : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _idUsuario;
		
		private string _idPerfil;
		
		private string _Nombre;
		
		private string _ApellidoPat;
		
		private string _ApellidoMat;
		
		private string _DNI;
		
		private string _Telefono;
		
		private string _Direccion;
		
		private string _Nick;
		
		private string _Contraseña;
		
		private EntityRef<tPerfil> _tPerfil;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidUsuarioChanging(string value);
    partial void OnidUsuarioChanged();
    partial void OnidPerfilChanging(string value);
    partial void OnidPerfilChanged();
    partial void OnNombreChanging(string value);
    partial void OnNombreChanged();
    partial void OnApellidoPatChanging(string value);
    partial void OnApellidoPatChanged();
    partial void OnApellidoMatChanging(string value);
    partial void OnApellidoMatChanged();
    partial void OnDNIChanging(string value);
    partial void OnDNIChanged();
    partial void OnTelefonoChanging(string value);
    partial void OnTelefonoChanged();
    partial void OnDireccionChanging(string value);
    partial void OnDireccionChanged();
    partial void OnNickChanging(string value);
    partial void OnNickChanged();
    partial void OnContraseñaChanging(string value);
    partial void OnContraseñaChanged();
    #endregion
		
		public tUsuario()
		{
			this._tPerfil = default(EntityRef<tPerfil>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idUsuario", DbType="VarChar(8) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string idUsuario
		{
			get
			{
				return this._idUsuario;
			}
			set
			{
				if ((this._idUsuario != value))
				{
					this.OnidUsuarioChanging(value);
					this.SendPropertyChanging();
					this._idUsuario = value;
					this.SendPropertyChanged("idUsuario");
					this.OnidUsuarioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idPerfil", DbType="VarChar(8) NOT NULL", CanBeNull=false)]
		public string idPerfil
		{
			get
			{
				return this._idPerfil;
			}
			set
			{
				if ((this._idPerfil != value))
				{
					if (this._tPerfil.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnidPerfilChanging(value);
					this.SendPropertyChanging();
					this._idPerfil = value;
					this.SendPropertyChanged("idPerfil");
					this.OnidPerfilChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombre", DbType="VarChar(30) NOT NULL", CanBeNull=false)]
		public string Nombre
		{
			get
			{
				return this._Nombre;
			}
			set
			{
				if ((this._Nombre != value))
				{
					this.OnNombreChanging(value);
					this.SendPropertyChanging();
					this._Nombre = value;
					this.SendPropertyChanged("Nombre");
					this.OnNombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ApellidoPat", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string ApellidoPat
		{
			get
			{
				return this._ApellidoPat;
			}
			set
			{
				if ((this._ApellidoPat != value))
				{
					this.OnApellidoPatChanging(value);
					this.SendPropertyChanging();
					this._ApellidoPat = value;
					this.SendPropertyChanged("ApellidoPat");
					this.OnApellidoPatChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ApellidoMat", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string ApellidoMat
		{
			get
			{
				return this._ApellidoMat;
			}
			set
			{
				if ((this._ApellidoMat != value))
				{
					this.OnApellidoMatChanging(value);
					this.SendPropertyChanging();
					this._ApellidoMat = value;
					this.SendPropertyChanged("ApellidoMat");
					this.OnApellidoMatChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DNI", DbType="VarChar(8)")]
		public string DNI
		{
			get
			{
				return this._DNI;
			}
			set
			{
				if ((this._DNI != value))
				{
					this.OnDNIChanging(value);
					this.SendPropertyChanging();
					this._DNI = value;
					this.SendPropertyChanged("DNI");
					this.OnDNIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Telefono", DbType="VarChar(12)")]
		public string Telefono
		{
			get
			{
				return this._Telefono;
			}
			set
			{
				if ((this._Telefono != value))
				{
					this.OnTelefonoChanging(value);
					this.SendPropertyChanging();
					this._Telefono = value;
					this.SendPropertyChanged("Telefono");
					this.OnTelefonoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Direccion", DbType="VarChar(50)")]
		public string Direccion
		{
			get
			{
				return this._Direccion;
			}
			set
			{
				if ((this._Direccion != value))
				{
					this.OnDireccionChanging(value);
					this.SendPropertyChanging();
					this._Direccion = value;
					this.SendPropertyChanged("Direccion");
					this.OnDireccionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nick", DbType="VarChar(30) NOT NULL", CanBeNull=false)]
		public string Nick
		{
			get
			{
				return this._Nick;
			}
			set
			{
				if ((this._Nick != value))
				{
					this.OnNickChanging(value);
					this.SendPropertyChanging();
					this._Nick = value;
					this.SendPropertyChanged("Nick");
					this.OnNickChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Contraseña", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string Contraseña
		{
			get
			{
				return this._Contraseña;
			}
			set
			{
				if ((this._Contraseña != value))
				{
					this.OnContraseñaChanging(value);
					this.SendPropertyChanging();
					this._Contraseña = value;
					this.SendPropertyChanged("Contraseña");
					this.OnContraseñaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tPerfil_tUsuario", Storage="_tPerfil", ThisKey="idPerfil", OtherKey="idPerfil", IsForeignKey=true)]
		public tPerfil tPerfil
		{
			get
			{
				return this._tPerfil.Entity;
			}
			set
			{
				tPerfil previousValue = this._tPerfil.Entity;
				if (((previousValue != value) 
							|| (this._tPerfil.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tPerfil.Entity = null;
						previousValue.tUsuario.Remove(this);
					}
					this._tPerfil.Entity = value;
					if ((value != null))
					{
						value.tUsuario.Add(this);
						this._idPerfil = value.idPerfil;
					}
					else
					{
						this._idPerfil = default(string);
					}
					this.SendPropertyChanged("tPerfil");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	public partial class spBuscar_DocenteResult
	{
		
		private string _idDocente;
		
		private string _Nombre;
		
		private string _ApellidoPat;
		
		private string _ApellidoMat;
		
		private string _DNI;
		
		private string _Telefono;
		
		private string _Direccion;
		
		public spBuscar_DocenteResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idDocente", DbType="VarChar(8) NOT NULL", CanBeNull=false)]
		public string idDocente
		{
			get
			{
				return this._idDocente;
			}
			set
			{
				if ((this._idDocente != value))
				{
					this._idDocente = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombre", DbType="VarChar(30) NOT NULL", CanBeNull=false)]
		public string Nombre
		{
			get
			{
				return this._Nombre;
			}
			set
			{
				if ((this._Nombre != value))
				{
					this._Nombre = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ApellidoPat", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string ApellidoPat
		{
			get
			{
				return this._ApellidoPat;
			}
			set
			{
				if ((this._ApellidoPat != value))
				{
					this._ApellidoPat = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ApellidoMat", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string ApellidoMat
		{
			get
			{
				return this._ApellidoMat;
			}
			set
			{
				if ((this._ApellidoMat != value))
				{
					this._ApellidoMat = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DNI", DbType="VarChar(8) NOT NULL", CanBeNull=false)]
		public string DNI
		{
			get
			{
				return this._DNI;
			}
			set
			{
				if ((this._DNI != value))
				{
					this._DNI = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Telefono", DbType="VarChar(12)")]
		public string Telefono
		{
			get
			{
				return this._Telefono;
			}
			set
			{
				if ((this._Telefono != value))
				{
					this._Telefono = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Direccion", DbType="VarChar(50)")]
		public string Direccion
		{
			get
			{
				return this._Direccion;
			}
			set
			{
				if ((this._Direccion != value))
				{
					this._Direccion = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
